[package]
name = "kanal-plus"
version = "0.2.0-beta2"
edition = "2021"
authors = ["Khashayar Fereidani"]
description = "Fork of kanal with extra features (drain_into_blocking, into_stream)"
repository = "https://github.com/acking-you/kanal"
documentation = "https://docs.rs/kanal-plus"
keywords = ["channel", "mpsc", "mpmc", "async"]
categories = ["concurrency", "data-structures", "asynchronous"]
license = "MIT"
readme = "README.md"

[dependencies]
branches = "0.3"
cacheguard = "0.1"
futures-core = { version = "0.3", optional = true }
lock_api = "0.4"

[dev-dependencies]
anyhow = "1.0"
criterion = "0.4"
crossbeam = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "test-util", "macros"] }
futures = "0.3"

[features]
async = ["futures-core"]
std-mutex = []
default = ["async"]

[[bench]]
name = "sync"
harness = false

[[bench]]
name = "async"
harness = false
